name: Reusable Python tests

on:
  workflow_call:
    inputs:
      runner:
        description: GitHub Actions runner label
        required: false
        type: string
        default: ""
      python-versions:
        description: JSON array of Python versions
        required: false
        type: string
        default: '["3.11", "3.12", "3.13", "3.14"]'

permissions:
  contents: read

env:
  ACTION_RUNNER_LABEL: ${{ inputs.runner || vars.DEFAULT_RUNNER || 'ubuntu-24.04' }}

jobs:
  linter:
    name: Code Linter
    runs-on: ${{ vars.DEFAULT_RUNNER || 'ubuntu-24.04' }}
    steps:
      - name: Check Out Repository
        uses: actions/checkout@v7.0.0
        with:
          persist-credentials: false

      - name: Bootstrap Runner
        uses: ./.github/actions/bootstrap
        with:
          python-version: "3.14"
          groups: lint

      - name: Run Linter
        run: ./scripts/lint.sh
        env:
          UV_NO_SYNC: "1"

  run-tests:
    strategy:
      fail-fast: false
      matrix:
        python-version: ${{ fromJSON(inputs.python-versions) }}
    name: Python ${{ matrix.python-version }}
    runs-on: ${{ inputs.runner || vars.DEFAULT_RUNNER || 'ubuntu-24.04' }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v7.0.0 # v7.0.0
        with:
          persist-credentials: false

      - name: Set up project
        uses: ./.github/actions/bootstrap
        with:
          python-version: ${{ matrix.python-version }}
          groups: test

      - name: Run tests
        run: |
          uv run --locked pytest
